apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-storage
  namespace: ml-training
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard

